/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rs.ac.bg.fon.ps.client.form;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import rs.ac.bg.fon.ps.client.controller.ClientController;
import rs.ac.bg.fon.ps.client.model.KlijentTableModel;
import rs.ac.bg.fon.ps.common.domain.GenericEntity;
import rs.ac.bg.fon.ps.common.domain.KategorijaKlijenta;
import rs.ac.bg.fon.ps.common.domain.Klijent;

/**
 *
 * @author ognje
 */
public class FrmKlijent extends javax.swing.JFrame {

    private KlijentTableModel ktm;
    private FrmPregledKlijenata parentForma;
    private Klijent klijentZaIzmenu;
    
    /**
     * Creates new form FrmKlijent
     */
    public FrmKlijent() {
       ktm = new KlijentTableModel();
        initComponents(); 
        
        pripremiFormu();
        ucitajKategorije();
        ucitajKlijente();
    }
    /*
    public FrmKlijent(FrmPregledKlijenata parentForma, Klijent ucitaniKlijent) {
        ktm = new KlijentTableModel();
        initComponents(); 
        pripremiFormu(); // Učitava nam kategorije u ComboBox kao i uvek

        this.parentForma = parentForma;
        this.klijentZaIzmenu = ucitaniKlijent;

        popuniFormu();
    }
    */
    /*
    public FrmKlijent(FrmPregledKlijenata parentForma, Klijent ucitaniKlijent) {
        ktm = new KlijentTableModel();
        initComponents(); 
        ucitajKategorije(); // Prvo učitaj kategorije u ComboBox

        this.parentForma = parentForma;
        this.klijentZaIzmenu = ucitaniKlijent;

        // 1. Popuni polja direktno iz prosleđenog objekta
        txtIme.setText(ucitaniKlijent.getIme());
        txtPrezime.setText(ucitaniKlijent.getPrezime());
        txtKontakt.setText(ucitaniKlijent.getKontakt());
        cmbKategorija.setSelectedItem(ucitaniKlijent.getKategorija());

        // 2. Otključaj polja da zubar može da kuca
        txtIme.setEnabled(true);
        txtPrezime.setEnabled(true);
        txtKontakt.setEnabled(true);
        cmbKategorija.setEnabled(true);

        // 3. Sakrij višak (dugmiće i tabelu)
        prilagodiFormuZaIzmenu();
    }
    */
    
    // Измењени конструктор у FrmKlijent
    public FrmKlijent(FrmPregledKlijenata parentForma, Klijent ucitaniKlijent, String mod) {
        ktm = new KlijentTableModel();
        initComponents(); 
        ucitajKategorije();

        this.parentForma = parentForma;
        this.klijentZaIzmenu = ucitaniKlijent;

        // Попуни поља подацима
        txtIme.setText(ucitaniKlijent.getIme());
        txtPrezime.setText(ucitaniKlijent.getPrezime());
        txtKontakt.setText(ucitaniKlijent.getKontakt());
        cmbKategorija.setSelectedItem(ucitaniKlijent.getKategorija());

        // ГЛАВНА ЛОГИКА ЗА МОДОВЕ
        if (mod.equals("IZMENA")) {
            prilagodiFormuZaIzmenu(); 
        } else if (mod.equals("BRISANJE")) {
            prilagodiFormuZaBrisanje(); // Овде све закључавамо и приказујемо дугме за брисање
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtIme = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPrezime = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtKontakt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cmbKategorija = new javax.swing.JComboBox<>();
        btnZapamti = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKlijent = new javax.swing.JTable();
        btnKreiraj = new javax.swing.JButton();
        btnSacuvaj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Ime:");

        txtIme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtImeActionPerformed(evt);
            }
        });

        jLabel2.setText("Prezime:");

        jLabel3.setText("Kontakt:");

        jLabel5.setText("Kategorija:");

        btnZapamti.setText("Dodaj");
        btnZapamti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZapamtiActionPerformed(evt);
            }
        });

        btnObrisi.setText("Obrisi");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        tblKlijent.setModel(ktm);
        jScrollPane1.setViewportView(tblKlijent);

        btnKreiraj.setText("Kreiraj");
        btnKreiraj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKreirajActionPerformed(evt);
            }
        });

        btnSacuvaj.setText("Sacuvaj");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cmbKategorija, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtKontakt))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(400, 400, 400))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnKreiraj, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnZapamti, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(96, 96, 96)
                                .addComponent(btnObrisi)
                                .addGap(18, 18, 18)
                                .addComponent(btnSacuvaj))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtKontakt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbKategorija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnZapamti)
                    .addComponent(btnObrisi)
                    .addComponent(btnKreiraj)
                    .addComponent(btnSacuvaj))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtImeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtImeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtImeActionPerformed

    private void btnZapamtiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZapamtiActionPerformed
        dodajKlijenta();
    }//GEN-LAST:event_btnZapamtiActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
        obrisiKlijenta();
    }//GEN-LAST:event_btnObrisiActionPerformed

    private void btnKreirajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKreirajActionPerformed
        kreirajKlijenta();
    }//GEN-LAST:event_btnKreirajActionPerformed

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed
        try {
        // Korak 10: Kontrola podataka
        if (txtIme.getText().isEmpty() || txtPrezime.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Систем не може да запамти клијента", "Грешка", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Korak 9: Unos (izmena) podataka u objekat
        klijentZaIzmenu.setIme(txtIme.getText().trim());
        klijentZaIzmenu.setPrezime(txtPrezime.getText().trim());
        klijentZaIzmenu.setKontakt(txtKontakt.getText().trim());
        klijentZaIzmenu.setKategorija((KategorijaKlijenta) cmbKategorija.getSelectedItem());

        // Korak 11 i 12: Poziv sistema da zapamti (UPDATE)
        ClientController.getInstance().zapamtiKlijenta(klijentZaIzmenu);

        // Korak 13: Poruka o uspehu
        JOptionPane.showMessageDialog(this, "Систем је запамтио клијента.", "Успех", JOptionPane.INFORMATION_MESSAGE);
        
        // Ako hoćeš da osvežiš tabelu u roditeljskoj formi nakon zatvaranja
        if(parentForma != null) {
            // Ovde bi mogao dodati metodu u FrmPregledKlijenata da ponovo učita tabelu
            parentForma.osveziTabelu();
        }
        
        this.dispose();

    } catch (Exception ex) {
        ex.printStackTrace();
        // Korak 13.1: Greška pri pamćenju
        JOptionPane.showMessageDialog(this, "Систем не може да запамти клијента.", "Грешка", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSacuvajActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmKlijent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmKlijent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmKlijent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmKlijent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmKlijent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKreiraj;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JButton btnZapamti;
    private javax.swing.JComboBox<KategorijaKlijenta> cmbKategorija;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblKlijent;
    private javax.swing.JTextField txtIme;
    private javax.swing.JTextField txtKontakt;
    private javax.swing.JTextField txtPrezime;
    // End of variables declaration//GEN-END:variables

    private void ucitajKategorije(){
        try {
            List<GenericEntity> lista = ClientController.getInstance().getAllKategorijaKlijenta();
            
            //System.out.println("Broj kategorija: " + lista.size());
            
            cmbKategorija.removeAllItems();
            for(GenericEntity ge: lista){
                cmbKategorija.addItem((KategorijaKlijenta) ge);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Greska pri ucitavanju kategorija klijenta");
            
        }
    }

    private void ucitajKlijente() {
        try {

            List<GenericEntity> lista = ClientController.getInstance().getAllKlijent();

            List<Klijent> klijenti = new ArrayList<>();

            for(GenericEntity ge : lista){
                klijenti.add((Klijent) ge);
            }

            ktm.setListaKlijenata(klijenti);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Greska pri ucitavanju klijenata");
        }
    }

    private void dodajKlijenta() {

        try {
            // KORAK 5: Zubar kontrolise da li je korektno uneo podatke
            if (txtIme.getText().trim().isEmpty() || txtPrezime.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Систем не може да запамти клијента.", "Грешка", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Pravimo klijenta od unetih podataka
            Klijent klijent = new Klijent();
            klijent.setIme(txtIme.getText().trim());
            klijent.setPrezime(txtPrezime.getText().trim());
            klijent.setKontakt(txtKontakt.getText().trim()); // Ako imas telefon
            
            // Uzimamo selektovanu kategoriju
            klijent.setKategorija((KategorijaKlijenta) cmbKategorija.getSelectedItem());

            // KORAK 6 i 7: Pozivamo sistem da zapamti klijenta
            ClientController.getInstance().zapamtiKlijenta(klijent);

            // KORAK 8: Sistem prikazuje poruku o uspehu
            JOptionPane.showMessageDialog(this, "Систем је запамтио клијента.", "Успех", JOptionPane.INFORMATION_MESSAGE);
            
            // Resetujemo formu ili je zatvaramo
            dispose(); 

        } catch (Exception ex) {
            ex.printStackTrace();
            // KORAK 8.1: Alternativni scenario (Pad servera ili baze)
            JOptionPane.showMessageDialog(this, "Систем не може да запамти клијента.", "Грешка", JOptionPane.ERROR_MESSAGE);
        }

    }

    private void izmeniKlijenta() {

        int row = tblKlijent.getSelectedRow();

        if(row == -1){
            JOptionPane.showMessageDialog(this,"Izaberite klijenta");
            return;
        }

        try {

            Klijent k = ktm.getKlijentAt(row);

            k.setIme(txtIme.getText());
            k.setPrezime(txtPrezime.getText());
            k.setKontakt(txtKontakt.getText());
            k.setKategorija((KategorijaKlijenta)cmbKategorija.getSelectedItem());

            ClientController.getInstance().zapamtiKlijenta(k);

            JOptionPane.showMessageDialog(this,"Klijent izmenjen");
            ocistiFormu();
            ucitajKlijente();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }

    private void obrisiKlijenta() {

        try {
        // Корак 9 & 10: Позив систему
        ClientController.getInstance().deleteKlijent(klijentZaIzmenu);

        // Корак 11: Порука о успеху
        JOptionPane.showMessageDialog(this, "Систем је обрисао клијента.", "Успех", JOptionPane.INFORMATION_MESSAGE);
        
        // Освежи табелу у форми за преглед
        if (parentForma != null) {
            parentForma.osveziTabelu();
        }
        
        this.dispose();

        } catch (Exception ex) {
            // Алтернативни сценарио 11.1
            JOptionPane.showMessageDialog(this, "Систем не може да обрише клијента.", "Грешка", JOptionPane.ERROR_MESSAGE);
        }

    }

   
    
    private void popuniFormu() {
        int row = tblKlijent.getSelectedRow();

        if (row != -1) {
            Klijent k = ktm.getKlijentAt(row);

            txtIme.setText(k.getIme());
            txtPrezime.setText(k.getPrezime());
            txtKontakt.setText(k.getKontakt());
            cmbKategorija.setSelectedItem(k.getKategorija());
        }
    }

    private void ocistiFormu() {
        txtIme.setText("");
        txtPrezime.setText("");
        txtKontakt.setText("");
        
        if (cmbKategorija.getItemCount() > 0) {
            cmbKategorija.setSelectedIndex(0);
        }
        tblKlijent.clearSelection();
    }

    private void pripremiFormu() {
        try {
            // Preduslov: Učitane su liste (KategorijaKlijenta)
            // Pretpostavljam da imas metodu getAllKategorija() u kontroleru
            List<GenericEntity> kategorije = ClientController.getInstance().getAllKategorijaKlijenta();
            cmbKategorija.removeAllItems();
            for (GenericEntity ge : kategorije) {
                cmbKategorija.addItem((KategorijaKlijenta) ge); // Kastuj u tvoju klasu KategorijaKlijenta ako treba
            }

            // Zaključavamo polja za unos dok zubar ne klikne "Kreiraj"
            txtIme.setEnabled(false);
            txtPrezime.setEnabled(false);
            txtKontakt.setEnabled(false);
           
           
            cmbKategorija.setEnabled(false);
            tblKlijent.setEnabled(false);

            // Dugmici
            btnKreiraj.setEnabled(true);
            btnZapamti.setEnabled(false);
        
            btnObrisi.setEnabled(false);
            btnSacuvaj.setEnabled(false);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Грешка при учитавању предвиђених података: " + ex.getMessage());
        }
    }

    private void kreirajKlijenta() {
        try {
            // KORAK 1 i 2: Zubar poziva sistem, sistem kreira klijenta
            // (Ako tvoj projekat zahteva da se sa servera povuce novi Klijent sa novim ID-jem, pozivas kontroler)
            // 1. Zovemo server da "pripremi" novog klijenta (ovo gađa KreirajKlijentaSO)
            Klijent noviKlijent = ClientController.getInstance().kreirajKlijenta();
            
            // Otključavamo formu za KORAK 4 (Zubar unosi podatke)
            txtIme.setEnabled(true);
            txtPrezime.setEnabled(true);
            txtKontakt.setEnabled(true);
            
            cmbKategorija.setEnabled(true);
            
            btnKreiraj.setEnabled(false);
            btnZapamti.setEnabled(true);
            btnObrisi.setEnabled(true);
            tblKlijent.setEnabled(true);

            // KORAK 3: Sistem prikazuje klijenta i poruku (OBAVEZAN TEKST)
            JOptionPane.showMessageDialog(this, "Систем је креирао клијента.", "Успех", JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception ex) {
            // KORAK 3.1: Alternativni scenario
            JOptionPane.showMessageDialog(this, "Систем не може да креира клијента.", "Грешка", JOptionPane.ERROR_MESSAGE);
            this.dispose(); // Prekida se izvrsenje scenarija
        }
    }
    
    private void prilagodiFormuZaIzmenu() {
        this.setTitle("Измена података о клијенту");
        btnSacuvaj.setText("Сачувај измене");
        btnSacuvaj.setVisible(true); // Proveri da li je vidljivo

        btnKreiraj.setVisible(false);
        btnZapamti.setVisible(false); 
        btnObrisi.setVisible(false);

        jScrollPane1.setVisible(false); 
        // Dodatno: smanji prozor pošto nema tabele
        this.pack(); 
    }
    
        private void prilagodiFormuZaBrisanje() {
        this.setTitle("Брисање клијента");

        // Сакривамо све што нам не треба
        btnKreiraj.setVisible(false);
        btnZapamti.setVisible(false);
        btnSacuvaj.setVisible(false); // Ово је оно дугме за Update
        jScrollPane1.setVisible(false);

        // Приказујемо само дугме за брисање и мењамо му изглед ако треба
        btnObrisi.setVisible(true);
        btnObrisi.setText("Обриши клијента заувек");

        // Закључавамо сва поља за куцање (зубар не сме да мења ништа пре брисања)
        txtIme.setEditable(false);
        txtPrezime.setEditable(false);
        txtKontakt.setEditable(false);
        cmbKategorija.setEnabled(false);

        this.pack();
    }
    
}



