/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rs.ac.bg.fon.ps.client.form;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import rs.ac.bg.fon.ps.client.controller.ClientController;
import rs.ac.bg.fon.ps.client.model.KlijentTableModel;
import rs.ac.bg.fon.ps.common.domain.GenericEntity;
import rs.ac.bg.fon.ps.common.domain.KategorijaKlijenta;
import rs.ac.bg.fon.ps.common.domain.Klijent;

/**
 *
 * @author ognje
 */
public class FrmPregledKlijenata extends javax.swing.JFrame {

    private KlijentTableModel ktm;

    /**
     * Creates new form FrmPregledKlijenata
     */
    public FrmPregledKlijenata() {
        ktm = new KlijentTableModel();
        initComponents();
        pripremiFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtPretraga = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cmbKategorija = new javax.swing.JComboBox<>();
        cbIme = new javax.swing.JCheckBox();
        cbKategorija = new javax.swing.JCheckBox();
        btnPretrazi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKlijenti = new javax.swing.JTable();
        btnPonisti = new javax.swing.JButton();
        btnPromeni = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Ime i prezime:");

        jLabel2.setText("Kategorija:");

        btnPretrazi.setText("Pretrazi");
        btnPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretraziActionPerformed(evt);
            }
        });

        tblKlijenti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblKlijenti.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKlijentiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKlijenti);

        btnPonisti.setText("Ponisti");
        btnPonisti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPonistiActionPerformed(evt);
            }
        });

        btnPromeni.setText("Izmeni");
        btnPromeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPromeniActionPerformed(evt);
            }
        });

        btnObrisi.setText("Obrisi");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPretraga)
                            .addComponent(cmbKategorija, 0, 112, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(btnPromeni))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbKategorija, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cbIme))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnPretrazi)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnObrisi))
                                    .addComponent(btnPonisti, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 102, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbIme))
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(cmbKategorija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPretrazi)
                            .addComponent(btnObrisi))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbKategorija)
                            .addComponent(btnPonisti))
                        .addGap(13, 13, 13)
                        .addComponent(btnPromeni)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziActionPerformed
        pretrazi();
    }//GEN-LAST:event_btnPretraziActionPerformed

    private void tblKlijentiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKlijentiMouseClicked
        // Корак 5: Зубар бира клијента (двоуклик)
        if (evt.getClickCount() == 2) {

            int odabraniRed = tblKlijenti.getSelectedRow();
            if (odabraniRed == -1) {
                return;
            }

            try {
                // Узимамо клијента директно из табеле
                KlijentTableModel ktm = (KlijentTableModel) tblKlijenti.getModel();
                Klijent izabraniKlijent = ktm.getKlijentAt(odabraniRed);

                // test
                // izabraniKlijent.setIme("НепостојећиКлијент123");
                // Корак 6 и 7: Систем тражи клијента 
                // (Шаљемо целог клијента у searchKlijent методу да бисмо га опет "провукли" кроз базу због правила СК јер су тако рекли на ТГ)
                List<GenericEntity> nadjeni = ClientController.getInstance().searchKlijent(izabraniKlijent);

                // Корак 8.1: Алтернативни сценарио
                if (nadjeni == null || nadjeni.isEmpty()) {
                    throw new Exception("Не постоји у бази.");
                }

                Klijent ucitaniKlijent = (Klijent) nadjeni.get(0);

                // Корак 8: Систем приказује поруку
                JOptionPane.showMessageDialog(this, "Систем је нашао клијента.", "Успех", JOptionPane.INFORMATION_MESSAGE);

                //и отвара ону нашу нову форму са подацима!
                new FrmDetaljiKlijenta(ucitaniKlijent).setVisible(true);

            } catch (Exception ex) {
                ex.printStackTrace();
                // Корак 8.1: Алтернативни сценарио грешке
                JOptionPane.showMessageDialog(this, "Систем не може да нађе клијента.", "Грешка", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_tblKlijentiMouseClicked

    private void btnPonistiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPonistiActionPerformed

        txtPretraga.setText("");
        cbIme.setSelected(false);
        cbKategorija.setSelected(false);
        if (cmbKategorija.getItemCount() > 0) {
            cmbKategorija.setSelectedIndex(0);
        }

        osveziTabelu();
    }//GEN-LAST:event_btnPonistiActionPerformed

    private void btnPromeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromeniActionPerformed
        // Корак 5: Зубар бира клијента
        int odabraniRed = tblKlijenti.getSelectedRow();

        if (odabraniRed == -1) {
            JOptionPane.showMessageDialog(this, "Морате изабрати клијента из табеле да бисте га променили.", "Упозорење", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            KlijentTableModel ktm = (KlijentTableModel) tblKlijenti.getModel();
            Klijent izabraniKlijent = ktm.getKlijentAt(odabraniRed);

            // Корак 6 и 7: Систем тражи клијента 
            List<GenericEntity> nadjeni = ClientController.getInstance().searchKlijent(izabraniKlijent);

            if (nadjeni == null || nadjeni.isEmpty()) {
                throw new Exception("Не постоји у бази.");
            }

            Klijent ucitaniKlijent = (Klijent) nadjeni.get(0);

            // Корак 8: Систем приказује поруку
            JOptionPane.showMessageDialog(this, "Систем је нашао клијента спремног за измену.", "Успех", JOptionPane.INFORMATION_MESSAGE);

            // Отварамо FrmKlijent
            new FrmKlijent(this, ucitaniKlijent, "IZMENA").setVisible(true);

        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Систем не може да нађе клијента.", "Грешка", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnPromeniActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
        int row = tblKlijenti.getSelectedRow();
        if (row != -1) {
            KlijentTableModel model = (KlijentTableModel) tblKlijenti.getModel();
            Klijent selektovaniKlijent = model.getKlijentAt(row);

            FrmKlijent frm = new FrmKlijent(this, selektovaniKlijent, "BRISANJE");
            frm.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Молимо вас, изаберите клијента за брисање.");
        }
    }//GEN-LAST:event_btnObrisiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPregledKlijenata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPregledKlijenata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPregledKlijenata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPregledKlijenata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPregledKlijenata().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnPonisti;
    private javax.swing.JButton btnPretrazi;
    private javax.swing.JButton btnPromeni;
    private javax.swing.JCheckBox cbIme;
    private javax.swing.JCheckBox cbKategorija;
    private javax.swing.JComboBox<KategorijaKlijenta> cmbKategorija;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblKlijenti;
    private javax.swing.JTextField txtPretraga;
    // End of variables declaration//GEN-END:variables

    private void pretrazi() {
        try {
            Klijent kriterijum = new Klijent();
            boolean barJedan = false;

            // Kriterijum 1: Ime / Prezime
            if (cbIme.isSelected() && !txtPretraga.getText().trim().isEmpty()) {
                kriterijum.setIme(txtPretraga.getText().trim());
                barJedan = true;
            }

            // Kriterijum 2: Kategorija
            if (cbKategorija.isSelected() && cmbKategorija.getSelectedItem() != null) {
                kriterijum.setKategorija((KategorijaKlijenta) cmbKategorija.getSelectedItem());
                barJedan = true;
            }

            if (!barJedan) {
                JOptionPane.showMessageDialog(this, "Морате изабрати бар један критеријум претраге.");
                return;
            }

            // KORAK 1, 2 i 3: Pozivamo sistem
            List<GenericEntity> listaGE = ClientController.getInstance().searchKlijent(kriterijum);

            // KORAK 4.1: Alternativni scenario (Nema rezultata)
            if (listaGE == null || listaGE.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Систем не може да нађе клијенте по задатим критеријумима.", "Обавештење", JOptionPane.ERROR_MESSAGE);
                ktm.setListaKlijenata(new ArrayList<>());
                return;
            }

            // Prikazujemo rezultate
            List<Klijent> nadjeniKlijenti = new ArrayList<>();
            for (GenericEntity ge : listaGE) {
                nadjeniKlijenti.add((Klijent) ge);
            }

            KlijentTableModel ktm = (KlijentTableModel) tblKlijenti.getModel();

            ktm.setListaKlijenata(nadjeniKlijenti);

            // KORAK 4: Sistem prikazuje poruku o uspehu
            JOptionPane.showMessageDialog(this, "Систем је нашао клијенте по задатим критеријумима.", "Успех", JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Грешка при претрази: " + ex.getMessage(), "Грешка", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void pripremiFormu() {
        try {
            // 1. Učitavamo kategorije u padajući meni
            List<GenericEntity> kategorije = ClientController.getInstance().getAllKategorijaKlijenta();
            cmbKategorija.removeAllItems();
            for (GenericEntity ge : kategorije) {
                cmbKategorija.addItem((KategorijaKlijenta) ge); 
            }

            KlijentTableModel ktm = new KlijentTableModel();
            tblKlijenti.setModel(ktm);

            // Šaljemo potpuno prazan objekat Klijent, pa će getWhereCondition vratiti "1=1"
            List<GenericEntity> listaGE = ClientController.getInstance().searchKlijent(new Klijent());

            if (listaGE != null && !listaGE.isEmpty()) {
                List<Klijent> sviKlijenti = new ArrayList<>();
                for (GenericEntity ge : listaGE) {
                    sviKlijenti.add((Klijent) ge);
                }
                ktm.setListaKlijenata(sviKlijenti);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Грешка при припреми форме: " + ex.getMessage());
        }
    }

    public void osveziTabelu() {
        try {
            // Uzimamo sve klijente iz baze
            List<GenericEntity> listaGE = ClientController.getInstance().searchKlijent(new Klijent());
            List<Klijent> sviKlijenti = new ArrayList<>();

            if (listaGE != null) {
                for (GenericEntity ge : listaGE) {
                    sviKlijenti.add((Klijent) ge);
                }
            }

            // Ubacujemo novu listu u tabelu
            KlijentTableModel ktm = (KlijentTableModel) tblKlijenti.getModel();
            ktm.setListaKlijenata(sviKlijenti);

        } catch (Exception ex) {
            System.out.println("Greska pri osvezavanju tabele: " + ex.getMessage());
        }
    }
}
